title: "【NAGOYA AI YOUTH CAMP 2025】AIでプログラミングを体験してみよう！"
summary: "NAGOYA AI YOUTH CAMP 2025で使用する教材です。この教材を通してまずはAIを使用してプログラミングを体験してみましょう！"
topics: [AI, HTML, CSS, JavaScript, 初心者]
published: true
price: 0
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 00_introduction
  - 01_setup
  - 02_what-is-chatgpt
  - 03_web-app-introduction
  - 04_web-introduction
  - 05_web-app-setup
  - 06_web-app-dev-html
  - 07_web-app-dev-css
  - 08_web-app-dev-js
  - 09_web-app-dev-custom
  - 10_tips
